# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - master
      - main
      - release/*
      - hotfix/*
      - dw/*
  paths:
    include:
      - sdk/iotspaces/

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*
      - hotfix/*
      - dw/*
  paths:
    include:
      - sdk/iotspaces/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: iotspaces
    Artifacts:
      - name: azure-arm-iotspaces
        safeName: azurearmiotspaces
