# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - master
      - main
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/batch/

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/batch/

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: batch
    Artifacts:
      - name: azure-batch
        safeName: azurebatch
