trigger: none

stages:
  - template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      PackageName: "@azure/container-registry"
      ServiceDirectory: containerregistry
      # Live tests do not exist yet. Remove the below line when live tests are added.
      UnsupportedClouds: 'Public,Canary'
      EnvVars:
        AZURE_CLIENT_ID: $(aad-azure-sdk-test-client-id)
        AZURE_TENANT_ID: $(aad-azure-sdk-test-tenant-id)
        AZURE_CLIENT_SECRET: $(aad-azure-sdk-test-client-secret)
